Create Side Bar Component
DSC-UTMap/utmap-website pull request #51
Opened 2021-02-07 21:44 UTC by Leila-U

- create sidebar component in `SideBar.js`
- add a hamburger button in `App.js` to open and close the sidebar

2021-02-07 21:59 UTC, RiddleMeDoo commented on utmap-client/src/components/pages/SideBar.js
> +const drawerWidth = 350;
Is this 350 pixels? Could you make it a percentage or em instead?

2021-02-07 22:06 UTC, RiddleMeDoo requested changes
- Interesting use of clsx. 
- I'm not sure if sidebar should appear on every page. Is it possible to have it in Calendar/Map pages only? (Either move the code or hide it in the landing page)
- There is a styling issue as well where it moves the calendar down when opened but it might be automatically fixed once we style the calendar to have margins. (so let's leave it like that)
- I would like the sidebar to be wider, maybe about a quarter of the screen. I will leave that to your discretion.

2021-02-08 01:35 UTC, RiddleMeDoo approved these changes

2021-02-08 04:14 UTC, ShahmeerShahid commented on utmap-client/src/components/pages/CalendarPage.js
> +	const classes = useStyles();
Fix indentation

2021-02-08 04:16 UTC, ShahmeerShahid approved these changes

2021-02-08 04:57 UTC, merged